name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']
body:
    - type: markdown
      attributes:
          value: 'Thanks for taking the time to fill out this bug report!'
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Tell / show what went wrong, screenshots / screen recordings are helpful!
          placeholder: What happened?
      validations:
          required: true
    - type: textarea
      id: how
      attributes:
          label: How?
          description: How can we replicate the issue?
          placeholder: e.x. 1. go to page XXX, 2. connect wallet, 3. ...
      validations:
          required: true
    - type: textarea
      id: what-expected
      attributes:
          label: What was Expected?
          description: What did you expect to happen?
          placeholder: What did you expect to happen?
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: shell
    - type: dropdown
      id: browsers
      attributes:
          label: What browser(s) are you seeing the problem on?
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - MetaMask Browser
              - Brave Browser
    - type: dropdown
      id: wallet
      attributes:
          label: What wallet are you seeing the problem on?
          multiple: true
          options:
              - MetaMask
              - Brave
