// import { PositionPoolIF } from './PositionPoolIF';
export interface PositionIF {
    chainId: string;
    ambient: boolean;
    askTick: number;
    bidTick: number;
    id: string;
    isBid: boolean;
    knockout: boolean;
    poolIdx: number;
    base: string;
    baseTokenLogoURI: string;
    quoteTokenLogoURI: string;
    quote: string;
    user: string;
    userEnsName: string;
    baseSymbol: string;
    quoteSymbol: string;
    poolPriceInTicks: number;
    lowRangeDisplayInBase: string;
    lowRangeShortDisplayInBase: string;
    highRangeDisplayInBase: string;
    highRangeShortDisplayInBase: string;
    lowRangeShortDisplayInQuote: string;
    lowRangeDisplayInQuote: string;
    highRangeDisplayInQuote: string;
    highRangeShortDisplayInQuote: string;
    tokenAQtyDisplay: string;
    tokenBQtyDisplay: string;
    baseTokenDecimals: number;
    quoteTokenDecimals: number;
    positionType?: string;
    positionLiqBase?: string;
    positionLiqQuote?: string;
}
