import { ChainSpec } from '@crocswap-libs/sdk';
import { useEffect, useState } from 'react';
import { memoizePoolStats } from '../../../../App/functions/getPoolStats';
import { useAppSelector } from '../../../../utils/hooks/reduxToolkit';
import { formatAmount } from '../../../../utils/numbers';
import styles from './PoolInfo.module.css';
import { BsArrowUpRight, BsStars } from 'react-icons/bs';
import trimString from '../../../../utils/functions/trimString';
import { DefaultTooltip } from '../../../Global/StyledTooltip/StyledTooltip';
import { ZERO_ADDRESS } from '../../../../constants';
// interface for props
interface PoolInfoPropsIF {
    chainData: ChainSpec;
    lastBlockNumber: number;
}
interface PoolInfoCardPropsIF {
    // eslint-disable-next-line
    title: any;
    // eslint-disable-next-line
    data: any;
}

const cachedPoolStatsFetch = memoizePoolStats();

// react functional component
export default function PoolInfo(props: PoolInfoPropsIF) {
    // pool info card--------------------

    const aprTitle = (
        <p>
            Avg. APR
            <BsStars color='#d4af37' />
        </p>
    );

    function PoolInfoCard(props: PoolInfoCardPropsIF) {
        return (
            <DefaultTooltip
                interactive
                title={
                    props.title === 'TVL:'
                        ? 'Total value of all tokens currently locked in the pool.'
                        : props.title === '24h Fees:'
                        ? 'Sum of fees generated by swaps in the last 24 hours.'
                        : props.title === '24h Swap Volume:'
                        ? 'Sum of USD equivalent value of all swaps in the last 24 hours.'
                        : props.title?.props?.children?.includes('Avg. APR')
                        ? 'Average Annual Percentage Rate for all positions in the pool.'
                        : ''
                }
                placement={'bottom'}
                arrow
                enterDelay={400}
                leaveDelay={200}
            >
                <div className={styles.card_container}>
                    <p className={styles.title}>{props.title}</p>
                    <h4 className={styles.info}>{props.data}</h4>
                </div>
            </DefaultTooltip>
        );
    }

    // end of pool info card--------------------

    const { chainData, lastBlockNumber } = props;

    const tradeData = useAppSelector((state) => state.tradeData);

    const baseTokenAddress = tradeData.baseToken.address;
    const quoteTokenAddress = tradeData.quoteToken.address;
    const baseTokenSymbol = tradeData.baseToken.symbol;
    const quoteTokenSymbol = tradeData.quoteToken.symbol;
    const baseTokenlogo = tradeData.baseToken.logoURI;
    const quoteTokenlogo = tradeData.quoteToken.logoURI;

    const [poolVolume, setPoolVolume] = useState<string | undefined>();
    const [poolTvl, setPoolTvl] = useState<string | undefined>();
    const [poolFees, setPoolFees] = useState<string | undefined>();
    const [poolAPR, setPoolAPR] = useState<string | undefined>();

    useEffect(() => {
        setPoolVolume(undefined);
        setPoolTvl(undefined);
        setPoolFees(undefined);
        setPoolAPR(undefined);
    }, [
        JSON.stringify({ base: tradeData.baseToken.address, quote: tradeData.quoteToken.address }),
    ]);

    const fetchPoolStats = () => {
        (async () => {
            const poolStatsFresh = await cachedPoolStatsFetch(
                chainData.chainId.toString(),
                baseTokenAddress,
                quoteTokenAddress,
                chainData.poolIndex,
                Math.floor(lastBlockNumber / 4),
            );
            const volume = poolStatsFresh?.volume;
            const volumeString = volume ? '$' + formatAmount(volume) : undefined;
            setPoolVolume(volumeString);
            const tvl = poolStatsFresh?.tvl;
            const tvlString = tvl ? '$' + formatAmount(tvl) : undefined;
            setPoolTvl(tvlString);
            const fees = poolStatsFresh?.fees;
            const feesString = fees ? '$' + formatAmount(fees) : undefined;
            setPoolFees(feesString);
            const apr = poolStatsFresh?.apy;
            const aprString = apr ? formatAmount(apr) + '%' : undefined;
            setPoolAPR(aprString);
        })();
    };

    useEffect(() => {
        fetchPoolStats();
    }, [
        lastBlockNumber,
        JSON.stringify({ base: tradeData.baseToken.address, quote: tradeData.quoteToken.address }),
    ]);
    const truncatedBaseAddress = trimString(baseTokenAddress, 6, 0, '…');
    const truncatedQuoteAddress = trimString(quoteTokenAddress, 6, 0, '…');

    const baseAddressWithTooltip = (
        <DefaultTooltip
            interactive
            title={
                <div>
                    <p>{baseTokenAddress}</p>
                </div>
            }
            placement={'right'}
            arrow
            enterDelay={400}
            leaveDelay={200}
        >
            <p>{truncatedBaseAddress}</p>
        </DefaultTooltip>
    );
    const quoteAdressWithTooltip = (
        <DefaultTooltip
            interactive
            title={
                <div>
                    <p>{quoteTokenAddress}</p>
                </div>
            }
            placement={'right'}
            arrow
            enterDelay={400}
            leaveDelay={200}
        >
            <p>{truncatedQuoteAddress}</p>
        </DefaultTooltip>
    );

    const poolComposition = (
        <div className={styles.pool_composition_container}>
            <p className={styles.title}>Pool Composition</p>
            <div className={styles.pool_composition}>
                <div className={`${styles.composition_row} ${styles.composition_row_header}`}>
                    <p>Token</p>
                    <p className={styles.right}>Balance</p>
                    <p className={styles.right}>Value</p>
                </div>
                <div className={styles.composition_row}>
                    <a
                        target='_blank'
                        rel='noreferrer'
                        href={
                            baseTokenAddress === ZERO_ADDRESS
                                ? 'https://goerli.etherscan.io/address/0xfafcd1f5530827e7398b6d3c509f450b1b24a209'
                                : `https://goerli.etherscan.io/token/${baseTokenAddress}`
                        }
                        className={styles.token_display}
                    >
                        {/* <img src="https://cryptologos.cc/logos/usd-coin-usdc-logo.png" alt=""  /> */}
                        <p>{baseTokenSymbol} </p>
                        <p> {baseAddressWithTooltip}</p>
                        <BsArrowUpRight size={10} />
                    </a>
                    <p className={styles.right}>...</p>
                    <p className={styles.right}>$...</p>
                </div>
                <div className={styles.composition_row}>
                    <a
                        target='_blank'
                        rel='noreferrer'
                        href={`https://goerli.etherscan.io/token/${quoteTokenAddress}`}
                        className={styles.token_display}
                    >
                        {/* <img src="https://cryptologos.cc/logos/usd-coin-usdc-logo.png" alt=""  /> */}
                        <p>{quoteTokenSymbol} </p>
                        <p>{quoteAdressWithTooltip}</p>
                        <BsArrowUpRight size={10} />
                    </a>

                    <p className={styles.right}>...</p>
                    <p className={styles.right}>$...</p>
                </div>
            </div>
        </div>
    );

    const baseTokenDisplay = (
        <section className={styles.token_display_container}>
            <div className={styles.token_info}>
                <img src={baseTokenlogo} alt={baseTokenSymbol} />
                <h3>{baseTokenSymbol}</h3>
                <p>Ethereum</p>
            </div>
            <a
                target='_blank'
                rel='noreferrer'
                href={
                    baseTokenAddress === ZERO_ADDRESS
                        ? 'https://goerli.etherscan.io/address/0xfafcd1f5530827e7398b6d3c509f450b1b24a209'
                        : `https://goerli.etherscan.io/token/${baseTokenAddress}`
                }
            >
                <p> {baseAddressWithTooltip}</p>
                <BsArrowUpRight size={10} />
            </a>
            <p>Balance</p>
            <h3>169.00</h3>
            <p>Value</p>
            <h3>$420,000</h3>
        </section>
    );

    return (
        <main className={styles.container} style={{ height: '250px' }}>
            {/* {poolComposition} */}
            <div className={styles.content}>
                {/* <PoolInfoCard title='24h Swap Volume:' data={poolVolume || '...'} />
                <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                <PoolInfoCard title='TVL:' data={poolTvl || '...'} />
                <PoolInfoCard title={aprTitle} data={poolAPR || '...'} /> */}
                <section>first card</section>
                <section>seconf card</section>
                <section className={styles.right_container}>
                    <div className={styles.right_container_top}>
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                        <PoolInfoCard title='24h Fees:' data={poolFees || '...'} />
                    </div>
                    <div>
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit consequuntur
                        dolorum corrupti voluptate soluta modi dicta debitis ullam aliquam rerum?
                    </div>
                </section>
            </div>
        </main>
    );
}
