name: Jest Tests
on:
    push:
        branches: [main]
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
            - name: Install modules
              run: yarn
            - name: Run tests
              run: yarn test
