name: Jest Tests
on:
    push:
        branches: [main]
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: yarn
            - name: Run tests
              run: yarn test
